export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';
export const PRODUCT_LIST= 'PRODUCT_LIST';
export const CHECK_PRODUCT_EXIST_IN_CART= 'CHECK_PRODUCT_EXIST_IN_CART';